#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# (c) Elicarlos Ferreira <elicarlos.dias@lynxmind.com> | <dias.elicarlos@gmail.com>
# License: GNU General Public License v2

import sys

from cmk_addons.plugins.n8n_cmk.special_agents.agent_n8n import main as agent_n8n_main

if __name__ == "__main__":
    sys.exit(agent_n8n_main())


